### ISSUE TITLE
Feature request: ability to enable request/response data in httpDependency

### ISSUE THREAD

**Issue by iamimbohacker** [Microsoft/ApplicationInsights-dotnet-server#1099]
Feature request: Ability to add additional data to http dependency on End-to-end transaction details page

##  Actual Behavior
Request content or response is not logged to the details.

## Expected Behavior
Ability to log httpclient request body and response in the dependency with httpType

**Comment by lmolkova** [comment]
This feature is implemented, here you can find an example on how to use it:

https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/900

Basically during TelemetryIntitialiers run you have access to HttpRequestMessage/HttpWebRequest and HttpResponseMessage/HttpWebResponse through OperationDetails:

`dependencyTelemetry.TryGetOperationDetail("HttpResponse", out var reponseObject)`

Http keys are:

```csharp
        public const string HttpRequestOperationDetailName = "HttpRequest";
        public const string HttpResponseOperationDetailName = "HttpResponse";
        public const string HttpResponseHeadersOperationDetailName = "HttpResponseHeaders";

```

Be careful: in some cases instead of HttpResponse we can only give you HttpResponseHeaders,
