### ISSUE TITLE
CommandText of SqlCommand only logged when CommandType = StoredProcedure

### ISSUE THREAD

**Issue by mterwoord** [Microsoft/ApplicationInsights-dotnet-server#123]
Why is the commandtext not logged for different kinds of commands?

Regards,
Matthijs ter Woord

**Comment by SergeyKanzhelev** [comment]
@mterwoord , we are using two different approaches to collect dependencies. First - using the EventSource-based tracing that .NET framework provide out of the box. This approach doesn't require any additional installation and configuration, but it allows to collect less data. Specifically - command text cannot be collected.

Second approach involve installation of [Status Monitor, startup task for cloud service or Azure WebApp extension](https://azure.microsoft.com/en-us/documentation/articles/app-insights-dependencies/#to-set-up-dependency-monitoring). Unfortunatly we do not support collection of command text during development on iisexpress.

**Comment by mterwoord** [comment]
I'm working on monitoring a .NET 4.6 WPF application. logging stored procedure names works fine, but logging normal sql queries doesn't. To me this seems odd...

**Comment by abaranch** [comment]
As Sergey mentioned autocollection without StatusMonitor is limited because there is not much that .NET framework exposes. ApplicationInsights has profiler based instrumentation where we are not limited to what is provided by the framework. Though StatusMontior enables profiler only for IIS based applications. We have a sample how to enable profiler for worker role process [here](https://github.com/Microsoft/ApplicationInsights-Home/tree/master/Samples/AzureEmailService). You can try to do the similar thing.

**Comment by SergeyKanzhelev** [comment]
I have a blog post about it: http://apmtips.com/blog/2015/01/05/track-dependencies-in-console-application/ These days instructions may be simplified a bit - let me know if you are interested. For WPF application enabling profiler can visibly slow down startup time though.

And we are in touch with SQL team to enable sql statements out of the box in future versions of .NET.
