### ISSUE TITLE
RoleInstance for Cloud Services sometimes populated with RoleName_IN_0 and sometimes with RD003FF...

### ISSUE THREAD

**Issue by zakimaksyutov** [Microsoft/ApplicationInsights-dotnet-server#168]
RoleInstance for Cloud Services sometimes populated with RoleName_IN_0 and sometimes with RD003FF...

**Comment by FrictionFree** [comment]
Note: We should maintain consistency between how the .net sdk logs role instance names and how WAD2AI reports the names of the same instances. Otherwise, we get logs and perf counters coming from the same nodes but appearing as it the nodes are different. Currently there is no consistency.

**Comment by SergeyKanzhelev** [comment]
The reason of inconsistency is that 
1. there is no reliable way to detect that application is running in Cloud Service
2. correctly load the same version of `ServiceRuntime.dll` as customer will attempt to load later

So SDK rely on customer code to load service runtime before calling our initializers. And in most cases it's true as the code will look like [this](https://github.com/Microsoft/ApplicationInsights-Home/blob/5f9cb502bf115777c1bbe4d6c3143901216a35cd/Samples/AzureEmailService/MvcWebRole/Global.asax.cs#L27):

``` csharp
TelemetryConfiguration.Active.InstrumentationKey = RoleEnvironment.GetConfigurationSettingValue("APPINSIGHTS_INSTRUMENTATIONKEY"); 
```

The idea of fixing this issue was to attempt to load Service Runtime into a separate AppDomain and then unload this domain. This approach should minimize an interference with the customer code.
