### ISSUE TITLE
2.2 Beta Sdks are overzealously truncating http dependency names

### ISSUE THREAD

**Issue by gardnerjr** [Microsoft/ApplicationInsights-dotnet-server#202]
Any http dependency to something like `https://bing.com/?q=whatever` just turns into dependency name `/`

    "baseType" : "RemoteDependencyData",
    "baseData" : {
        "ver" : 2,
        "name" : "/",
        "id" : "Sh8PExRj764=",
        "data" : "https://bing.com/?q=fabrikamfiber",
        "duration" : "00:00:00.3321811",

**Is this intentional?** it doesn’t seem like a great idea, as you’d end up with a lot of dependencies aggregating together as just `/` even though they *went to different hosts*.  Right now `https://twitter.com/?q=whatever` would also turn into the same “name” even though they are *vastly different* dependencies.

Previous SDKs appear to be putting the whole uri as the name, like `https://fabrikamaccount.blob.core.windows.net:443/fabrikamfiber?restype=container`

The new sdk turns that into name = `fabrikamaccount/fabrikamfiber`

This seems like overkill, like the sdk is making assumptions about http host names and paths that don't always hold.  I don't think the name of a dependency should ever get truncated to just `/`

It would make sense for me for the SDK to truncate the name field to remove *query parameters*, so that you end up with `https://bing.com` and `https://fabrikamaccount.blob.core.windows.net:443/fabrikamfiber` but it seems odd to truncate it any further than that.

**Comment by SergeyKanzhelev** [comment]
Yes, this was an intentional change to align it with how the corresponding request names looks. Application map will use `target` field and we may need to change "slowest" resources table in UI to include the target into the corresponding query.


Just for the reference - this is how it looks with older SDK:

|    name                 |    value                   |
|------------------------------|-----------------------------------------------|
|    type                      |    HTTP                                       |
|    target                    |    bing.com                                   |
|    name                      |    https://bing.com                           |
|    data                      |    https://bing.com/?q=fabrikamfiber          |
|    success                   |    True                                       |
|    resultCode                |    200                                        |
|    duration                  |    152.2956                                   |
|    performanceBucket         |    <250ms                                     |
|    sdkVersion                |    rddf:   2.1.0.363                          |

**Comment by gardnerjr** [comment]
given that "name" is the field used by all of the search and metrics views, this seems like it might need some more thought in the new sdks?  if name is going to just be / then people are going to just switch to using some other field, and 

People will gradually switch from one sdk to another, so if you make a dramatic change like this, suddenly everyone's charts+queries are going to do really strange things, as all of the dependencies that used to say `https://bing.com` or `https://twitter` now disappear from your graphs, and everything looks like it pointing to a local request of `/` which definitely is not true

Request names I understand, because those are generally requests *in your own code*.  And the name still isn't just `/` for your own requests, it would generally be `GET [id]` or something more useful than just `/`.  So this doesn't match generated request names anyway.

Trying to make dependency names match them *just because you can* doesn't make sense to me. Generally the http dependencies are urls that are *not under your control*, so seeing all of my outbound calls to twitter and bing suddenly show up as `/` doesn't help me in any way.  this will just make everyone switch to using another field.  And if everyone does that, then it was pointless to change the behavior of name at all if nobody uses it after this change.  

It sounds like there's a plan for Application Map in the portal, but what about everything else that exists? in the Portal: Search, Metrics Explorer, Dependency grids, in VS: search, trends, in AA: any query anyone already has against dependencies, possibly pinned to a dashboard somewhere.

If all the tools and queries all have to switch to using 'target' and that wasn't populated by other sdks, or other versions of the asp.net sdk, this means you have really strange behaviors of the tools across the sdks. Is the backend is going to need to do all this work to populate target for all the other sdks and versions of the asp.net sdks?

**Comment by SergeyKanzhelev** [comment]
I'm waiting for other opinions in the thread... 

Looking at specific example `https://bing.com/?q=fabrikamfiber` it may look unnatural. However sending host name for the `https://secure.bank.com/login/sign-in/` instead of `/login/sign-in/` is equally strange. 

The logic currently implemented will also help to compare the same dependency name in different environments when the only difference in calls is a host name of a dependency.

Also duplicating data sent with events ultimately costs money. You can always run a query like this in AA `dependencies | extend fullName = strcat(target, " ", name) | summarize sum(count) by fullName` to return the past behavior. But you cannot cut the field off the data we send that easy to save money.

Do you have a suggestion for the better logic here? Logic that will work fine in scenarios I listed as well as in your case.

**Comment by gardnerjr** [comment]
My suggestion is to leave at least *part* of the host name intact in the name field to disambiguate things that might just be a short and non-obvious path.  if you don't have at least part of the host name, the name isn't going to be unique enough to do any meaningful aggregation on name alone. 

if i have amazon and twitter and facebook and other things as dependencies, and suddenly they are all just partial paths, like `/login`, or even just the first part of the host, which might be "m.facebook", resulting in `m/login`, then seeing the dependency names is going to be useless, because the first part of the path might not be very unique at all ("secure" or "mobile" or "login" like a lot of the services have for their top level hostnames.  if the shortened name was even top level domain name and the first part of the path, that's probably good enough "facebook.com/login"  (i realize that's exactly backwards for azure things, where the first part of the domain is the actual unique and useful thing, but those already have special processing to account for that...)

This might be one where instead of just suggestions, we might need to do a meta-analysis of data we have internally about what the various outcomes would be given the possibilities.  if you used the new behavior against existing dependencies across internal services, what information would you lose?  behaviors, tools, scripts, pinned charts, etc will have to be redone to work?

I'm not sure about the "duplicating data ultimately costs money" as an argument here.  Yes, everything cots money.  But removing built in usefulness and making a non-helpful field just means people will add custom properties to store it anyway, and now you're storing a non-helpful field *and* a custom field name *and* that value in custom properties, which ultimately costs even more money. (see other things that have been removed, like "User Agent").  If the name field isn't useful, why not just remove the name field entirely and just use "target" or "data" as the name?

**Comment by dnduffy** [comment]
The question I would ask is: "What is intuitive for customers?"
As an end-user I expect a "name" field to have a value that is useful, I also expect it to be the first field I would try when developing or querying data.
From the examples given above in the conversation, my intuitive expectation is that "name" would contain at least the fully qualified domain name.  Where we want to put data and what we feel is a good model should come second to a good customer experience.  The best data model in the world with the least amount of redundancy won't mean anything if we break customers' experiences or alienate them with non-intuitive requirements.

**Comment by SergeyKanzhelev** [comment]
For the http dependency you'd typically have code like this:

``` csharp
var webRequest = CreateWebRequest(ctx.Endpoint, query, {params});
webRequest.GetResponseAsync();
```

So you think of dependency name as `query` and this dependency is calling `ctx.Endpoint`. 

That is the idea. I see how it breaks when you have multiple services where operation is defined by domain name. Like in `bing` case - actual operation name is `Search` or `Bing`

Denormalizing of the data to optimize the UI is not good approach. I realize it may break some charts, but this will be an intentional update for the customer. Maybe we can have an instruction how to write telemetry initializer that will return things to what they were before.

The argument that our failure to update UI to account for target costs customer extra bytes to be sent with every dependency is also weak for me.

So maybe we can have a logic that includes domain name for `/` path? Or any other heuristics?

**Comment by dnduffy** [comment]
The "type" tells us it is a URL, "target" tells us the host, "name" tells us the path on the host, and "data" has some redundancy but ultimately contains the query parameters.  No data is missing and the model extends to types which are not URL's.
