### ISSUE TITLE
2.2.0-beta4 stops reporting CPU for web apps

### ISSUE THREAD

**Issue by zakimaksyutov** [Microsoft/ApplicationInsights-dotnet-server#225]
I have WebApp with 2 instances. First, one instance stopped reporting CPU. In some time both instances stopped reporting CPU.

**Comment by SergeyKanzhelev** [comment]
I have suspicion that this bug can be related to https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/209. We have a report that sometimes exception happens when we are trying to get the counter value. This exception may cause the collection logic to mark counter as "bad". I remember we had this feature to mark counters as "bad" for the regular performance counters after the number of attempts.

Just a thought. To validate - I'd suggest to enable warning or even informational level traces for the diagnostics listener module.

**Comment by cijothomas** [comment]
ok.. so i was able to REPRO this issue.. CPU simply stopped reporting after few minutes, whereas other metric (eg:PROCESS PRIVATE BYTES) are fine..

**Comment by cijothomas** [comment]
Restarting the WebApp temporarily brings back the CPU Counters ...

**Comment by cijothomas** [comment]
The root cause is found. Overflow of 'int' variable used to hold cpu time caused this. Will send pr with the fix.

**Comment by cijothomas** [comment]
For AzureWebApp we calculate CPU% by reading CPUTime+KernelTime from AzureWebApp environment variables, and doing the delta between consecutive reads and dividing it by the time between the reads. 

The variable used to store the value read from AzureWebApp environment variable was an int – after few minutes of starting, the value returned would overflow int, and we hit exception.
Fix is trivial - replace int with double. (all counters are double anyways)

**Comment by cijothomas** [comment]
Fixed here: https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/232
(it also fixed several other Exception handling logic as well)
