### ISSUE TITLE
2.2.0-beta4 does not distinguish Web App isntances

### ISSUE THREAD

**Issue by zakimaksyutov** [Microsoft/ApplicationInsights-dotnet-server#226]
I have WebApp with 2 instances. Azure Portal Application Insights Servers Page shows only one.

**Comment by cijothomas** [comment]
Reproed this in cijosdktest1 (AI application name).

**Comment by cijothomas** [comment]
Newly added AzureWebAppRoleEnvironmentTelemetryInitializer is setting roleinstancename from the Azure ENV variable "WEBSITE_HOSTNAME", this will be same across instances, so all instances would be treated as same.
Need to Investigate why AzureRoleEnvironmentTelemetryInitializer did not initialize the roleinstancename-AzureWebAppRoleEnvironmentTelemetryInitializer wont initialize if already populated.

**Comment by cijothomas** [comment]
AzureRoleEnvironmentTelemetryInitializer is valid only for Azure CloudServices. so AzureWebAppRoleEnvironmentTelemetryInitializer will populate roleinstance name to something not unique across instances.
The fix would be to populate the environment variable "WEBSITE_INSTANCE_ID", instead of "WEBSITE_HOSTNAME".
Ref:https://github.com/projectkudu/kudu/wiki/Azure-runtime-environment#website-environment-variables

**Comment by cijothomas** [comment]
Commenting out WebAppRole initializer in AI.config (shown below) will be the workaround until the fixed sdk is published.
