### ISSUE TITLE
What do you guys think about the idea of the user being able to assign a weightage (severity level) to exceptions

### ISSUE THREAD

**Issue by nizarq** [Microsoft/ApplicationInsights-dotnet-server#231]
Every system emits some exceptions as noise. Overtime the administrators learn to ignore them. 
Also while one is writing code, while sending exception telemetry, the user might have an inkling of the relative importance of the exception being logged. While TraceTelemetry allows for a severity level, exception telemetry does not. 

Do folks think it is useful to have an optional severity level for exceptions?

**Comment by drwill-ms** [comment]
Our team logs some exceptions that shouldn't be perceived as service errors, but we want to know more information. Because all exceptions are treated as "critical" in AI, we log them instead in traces. It would be nice to be able to specify a severity level with exceptions so they could be treated differently.

**Comment by SergeyKanzhelev** [comment]
See example here: https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/54bcb3e4b2d3e02862d65663c65b32b0ee4afac9/src/Adapters/Log4NetAppender.Shared/ApplicationInsightsAppender.cs#L96-L113

``` csharp
ExceptionTelemetry excT = new ExceptionTelemetry(exc) { SeverityLevel = SeverityLevel.Informaitonal; } 
telemetryClient.TrackException(excT);
```
