### ISSUE TITLE
APPINSIGHTS_INSTRUMENTATIONKEY AppSetting overrides ikey specified in code

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet-server#236]
1. Create 4.6 Web Application, enable Application Insights SDK 2.2 Beta 4 and specify  in Global.asax.cs:   
2. ``TelemetryConfiguration.Active.InstrumentationKey = "ikey1";``

4. Publish to Azure WebApp and verify that telemetry is being sent to ikey1
5. Add AppSetting to WebApp: APPINSIGHTS_INSTRUMENTATIONKEY pointing to ikey2

**Expected**: telemetry continues to be sent to ikey1, because settings in code take priority
**Actual**: telemetry now is being sent to ikey2, while QuickPulse events continue to go to ikey1.

**Comment by SergeyKanzhelev** [comment]
Since I took a look at code anyway - there are two places we set the key from the env variable:

This will not respect `TelemetryConfiguration.Active.InstrumentationKey = "ikey1";`, but will work when you set `new TelemetryClient("ikey1").TrackTrace("trace")`:

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Core/Managed/Shared/TelemetryClient.cs#L382-L387

This logic will not "override" the setting from the configuration file, but `TelemetryConfiguration.Active.InstrumentationKey = "ikey1";`,  will override it:

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/de488729c28b721a758e0024ea2d4f79909ff797/src/Core/Managed/Net40/Extensibility/Implementation/TelemetryConfigurationFactory.cs#L76-L81

So clearly the code needs to be refactored and we need unit tests that will "describe" the expected behavior

**Comment by dnduffy** [comment]
There is one small problem here, how do you tell the difference between a value in TelemetryConfiguration.Active.InstrumentationKey that was set explicitly in code from one that TelemetryConfigurationFactory.Instance.Initialize placed there from reading the config entry?

**Comment by dnduffy** [comment]
I've changed the logic and updated the unit tests.
Pull request is here: https://github.com/Microsoft/ApplicationInsights-dotnet/pull/379
