### ISSUE TITLE
WebApp PerfCounters - exception handling is not consistent with Standard PerfCounter

### ISSUE THREAD

**Issue by cijothomas** [Microsoft/ApplicationInsights-dotnet-server#237]
1. The messages logged when 1st time a counter is attempted to be registered is different for WebApp vs Standard.

2. After initial registration, any counter marked as 'bad' will be re-attempted once in 5 min. If this read fails, StandardPerfCollector reports error 'CounterRegistrationFailed', but WebApp reports 'UnknownErrrorEvent', and 'FirstReadFailed'. This would make very difficult to debug if things go bad for a customer.

**Comment by kartang** [comment]
The reason we used different registration messages is to distinguish between the total usage of standard counters vs web app counters. The same is applied for failures as well. We have an additional event for failed counter reads/registration, because, there is a scope to create a user actionable event if the target counter is not in the supported list of web app counters (which is different from failed registration/read).

**Comment by cijothomas** [comment]
@kartang to distinguish between usage of standard vs webapp, we had sdk version pre-fix.

**Comment by cijothomas** [comment]
After initial registration, any counter marked as 'bad' will be re-attempted once in 5 min. If this read fails, StandardPerfCollector reports error 'CounterRegistrationFailed', but WebApp reports 'UnknownErrrorEvent', and 'FirstReadFailed'. This would make very difficult to debug if things go bad for a customer.

-This statement was incorrect, both WebApp and Standard handles this similar way. PerformanceCounterFirstReadFailed is whats reported by both.
