### ISSUE TITLE
[Exception statistics] Check the Exception.Data is writable

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#338]
The ExecutionEngineException, OutOfMemoryException, StackOverflowException and ThreadAbortException classes always return null for the value of the Data property. Need to fall back to ConditionalWeakTable.

Also check IsReadOnly on it

**Comment by pharring** [comment]
Thanks for finding that. As you know, I have some other code that uses that technique, so I'll have to rework it too. I'd like to continue to use the ```Data``` dictionary when it's available and fall back to the CWT only when necessary.

To be clear, I don't see an implementation where ```.Data``` is null. Only that sometimes the ```.Data``` dictionary can be an empty, read-only dictionary. In which case, as you say, we can check for ```IsReadOnly```.

Dev notes:
I see in the implementation of [Exception.Data](https://github.com/dotnet/coreclr/blob/68f72dd2587c3365a9fe74d1991f93612c3bc62a/src/mscorlib/src/System/Exception.cs#L147) a check for ```IsImmutableAgileException(this)```. That results in a native call to check for one of the [pre-allocated exceptions](https://github.com/dotnet/coreclr/blob/2efbb9282c059eb9742ba5a59b8a1d52ac4dfa4c/src/vm/clrex.cpp#L546). I see the 4 exceptions you mentioned plus a "rude" ThreadAbortException and a [pre-allocated base exception](https://github.com/dotnet/coreclr/blob/a9b25d4aa22a1f4ad5f323f6c826e318f5a720fe/src/vm/vars.hpp#L448).

**Comment by SergeyKanzhelev** [comment]
Another dev note: here is a PR that takes use of CWT out: https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/296 for a reference to implement the fallback logic

**Comment by pharring** [comment]
BTW, I did look into this for my own code. I found it impossible to actually create one of those pre-defined exceptions in testing. (OutOfMemory, ThreadAbort, StackOverflow. I didn't try ExecutionEngineException) e.g. You can create _an_ OutOfMemoryException (either by throwing it yourself, or causing an array to grow beyond limits), but it's not actually the pre-allocated one - it still has a writable Data dictionary.
In practice, even if you did catch one of these and put it in a CWT, it'll never be finalized, so the dependent object will never get cleaned up.
That leads to the next problem: If you tag one of them as "handled", you'll never be able to clear that tag. i.e. You could only ever catch and tag the first of a given type. You can't distinguish it from another occurrence of that same exception because it has (by my reading of the code) reference identity. At least, that's my understanding. Like I said, I couldn't actually create one of them in testing.

**Comment by SergeyKanzhelev** [comment]
I mostly concerned about `ThreadAbortException` for the web scenarios. Raise in the # of those indicates the increased number of timing out clients.

How have you tried the `ThreadAbortException`? Have you tried terminating the task or thread?

**Comment by pharring** [comment]
Yes. I did try ```ThreadAbortException``` by calling ```System.Thread.Abort()````. In the 1st chance exception handler, the Data member was writable. I'll have to take a look at how ASP.NET actually aborts long-running requests.
I presume you actually saw the case where ```.Data``` was read-only in your statistics, yes?

**Comment by SergeyKanzhelev** [comment]
No, I haven't seen it. I deducted (or rather inducted) =) And also I haven't seen any `ThreadAbortException`s in my applications. Which made me start deducting (or inducting)....

**Comment by pharring** [comment]
This may be moot, then. I have coded defensively in my code, both checking for null and checking the .IsReadOnly property, but I have not been able to generate unit tests to cover those cases.
