### ISSUE TITLE
We should consolidate the instances of OperationCorrelationTelemetryInitializer.

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-dotnet-server#456]
There is a copy of OperationCorrelationTelemetryInitializer in this SDK and also in the .NET Core SDK.  They are a bit different but also have shared logic and copy/pasted code.

**Comment by xiaomi7732** [comment]
Refer commit 2097faf for a partial effort. (At least we can make advantage of the comments added there :-))

**Comment by lmolkova** [comment]
- [Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/151509eac5e23fcbd09f3a8989a35d1099703957/src/Core/Managed/Shared/Extensibility/OperationCorrelationTelemetryInitializer.cs) in BaseSDK purpose now is to initialize telemetry from `Activity.Current` (or `CallContext` on NET4.0)
- [Microsoft.ApplicationInsights.Web.OperationCorrelationTelemetryInitializer](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/Web/Web.Shared.Net/OperationCorrelationTelemetryInitializer.cs) in Web SDK serves other purposes: in initializes telemetry if Activity.Current was lost in ASP.NET Classic native/managed thread hops. You can find nore details in comment in the code. This code is specific to AspNet Classic and it cannot live anywhere except Web SDK.
Unfortunately, it also serves as a public API to set custom headers. So we can not remove it...
*  [Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.OperationCorrelationTelemetryInitializer](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/OperationCorrelationTelemetryInitializer.cs) should indeed be changed. It now serves 2 purposes:
  - sets operation Id, root and parent that is in fact redundant and wrong, since it's done in Base SDK from current Activity - we will address this in the AspNetCore SDK changes for 2.2.
  - parses cross-component correlationId - this should be moved to hosting layer: I believe it is a mistake that it is called for each telemetry, it should be called once per request. 
So, this telemetry initializer should go away completely

This leaves us with 2 OperationCorrelationTelemetryInitializers: Web and Base that have different logic and no copy-paste code and we cannot remove any of them.

**Comment by OskarKlintrot** [comment]
Are `Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer` and `Microsoft.ApplicationInsights.Web.OperationCorrelationTelemetryInitializer` mutually exclusive or can they be used together? In my config-file for a WebApi-project (net461) I have `Microsoft.ApplicationInsights.Web.OperationCorrelationTelemetryInitializer` but the request telemetry and log from `ILogger` (using the ApplicationInsightsProvier) didn't get grouped together as one operation. I just tried to add `Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer` in code to see what would happen (I can't really find any useful docs for Microsofts own TelemetryInitializers, maybe I just haven't found it yet?) but then neither the request nor the log-message appeared on Application Insights.

**Comment by Dmitry-Matveev** [comment]
@OskarKlintrot, typically, you'd need to use the set of the initiazers that comes with the latest clean installation of SDK. So you can have a test project with 2.9.1 to check what's the current set.

@lmolkova may know why ILogger messages are not correlated (coud it be that overarching Activity is lost by the moment Initializer runs for Trace Telemetry coming from ILogger)?

**Comment by lmolkova** [comment]
when you use ILogger (Microsoft.extensions.logging.applicaitoninsights), you have to configure `Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer` explicitly.

```csharp
 services.Configure<TelemetryConfiguration>(
        (config) =>
        {                            
            config.TelemetryInitializers.Add(new MyTelemetryInitalizer());
        }
    );
```

**Comment by OskarKlintrot** [comment]
That makes sense, thanks!
