### ISSUE TITLE
OnBeginSql callbacks sometimes fail being unable to load System.Diagnostics.DiagnosticSource

### ISSUE THREAD

**Issue by Dmitry-Matveev** [Microsoft/ApplicationInsights-dotnet-server#672]
The following trace messages often appeared in AI Web SDK telemetry:

Callback `OnBeginSql` failed for id='<Different Ids Here>'. Exception: System.IO.FileNotFoundException: Could not load file or assembly `System.Diagnostics.DiagnosticSource, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51` or one of its dependencies.

![image](https://user-images.githubusercontent.com/12158043/29476974-3046c126-841b-11e7-8a56-34ea390b3bf8.png)

**Comment by lmolkova** [comment]
.NET SQL [manages app domains](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-clr-appdomains-transact-sql) on its own, so this issue should be dup of #613 with a similar workarounds.

**Comment by SergeyKanzhelev** [comment]
@lmolkova I cannot believe it. So SQL creates an app domain for query executions? I wonder - do you know why they are doing it?

**Comment by SergeyKanzhelev** [comment]
BTW, even if it creates app domain for the query execution - why it fails? Is it trying to access the value from CallContext? 

Reopening temporarily for the explanaition

**Comment by lmolkova** [comment]
> There are several types of CLR integration managed database objects. For general information about these objects, see Building Database Objects with Common Language Runtime (CLR) Integration. Whenever these objects are executed, SQL Server creates an AppDomain under which it can load and execute the required code. The isolation level for an AppDomain is one AppDomain per database per owner. That is, all CLR objects owned by a user are always executed in the same AppDomain per-database (if a user registers CLR database objects in different databases, the CLR database objects will run in different application domains). An AppDomain is not destroyed after the code finishes execution. Instead, it is cached in memory for future executions. This improves performance.

AppDomains may be reused and the issues we have seen before are related to the cross AppDomain calls, it does not matter when AppDomain was created.

My assumption was that callback for sql call happens in another appdomain that may have no knowledge about Activity/DiagnosticSource and crashes trying to resolve it.
But looking more precisely, in such case we should get  `SerializationException` rather than `FileNotFound` so it may be a completly different problem.

Perhaps we should keep it open until we completely understand the issue.

We don't see this issue with our test/demo projects and sql dependencies are tracked, so there is something special about the setup where the issue reproduces.
Or it might happen for a limited set of operations and does not noticeably affect sql dependency tracking.

@Dmitry-Matveev do we know the .NET version for this issue? If it's .NET 4.6 we can reject CallContext-related issues.

Also, a number of customers affected would really help. There could always be a rare case when e.g. version of AppInsights SDK was manually updated, but dependencies were not.

**Comment by MS-TimothyMothra** [comment]
@Dmitry-Matveev please take a look. :)

**Comment by Dmitry-Matveev** [comment]
Based on our telemetry, this issue does not seem to reproduce in 2.5+. Closing the issue.
