### ISSUE TITLE
Remove unsupported standard counters from Perf Collector to minimize overhead of SDK

### ISSUE THREAD

**Issue by kartang** [microsoft/ApplicationInsights-dotnet-server#7]

**Comment by olegsych** [comment]
More specifically, the perf counter collector should not track any counters implicitly. We shouldn't have a magic default set of counters hardcoded internally. Every counter should be an explicit opt in either in the application code or in the config file. This should be both simpler and easier to use than what we have today.

**Comment by cijothomas** [comment]
This is more relevant now - lot of people are running app inside containers and from inside containers TotalCPU/TotalMemory counters are not possible to be collected. This causes SDK to spit out 2 Error traces to AI. While 2 traces may appear nothing, it is significant noise to traces (and cost) since these error traces occurs on every application start/container start.

SDK should not have 'hidden default' list of counters.

**Comment by cijothomas** [comment]
Related - https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/687

**Comment by cijothomas** [comment]
SF clusters contains co-located AI Apps in same machine, and each of them will collect and send perf counters. This can potentially increase telemetry volume. This should be treated with high priority for 2.6.0 as multiple customers reported issues now.

**Comment by mosentok** [comment]
this issue was closed 5 days ago. today i am still getting default performance counters. why is this closed if there are still default performance counters?

**Comment by cijothomas** [comment]
only unsupported counters are removed. the default counters are still collected. You need to turn off perf counter module, if you do not want counters at all.
