### ISSUE TITLE
AI: Performance counter is not available in the web app supported list. Counter is \Processor(_Total)\% Processor Time.

### ISSUE THREAD

**Issue by ebashmakov** [Microsoft/ApplicationInsights-dotnet-server#757]
The Application Insights client generates unnecessary traces with the following message:
```
AI: Performance counter is not available in the web app supported list. Counter is \Processor(_Total)\% Processor Time.
```
And when the client sends the traces to AI it uses incorrect context (`NodeName`, `RoleInstance`, and `RoleName`).

## Repro Steps
1. Create a FunctionApp application
2. Install Microsoft.ApplicationInsights package
3. Create AzureFunctions and AppInsights instances
4. Deploy the app and set up `APPINSIGHTS_INSTRUMENTATIONKEY`
5. Filter the telemetry by `Trace` in the Azure Portal

**Example**: https://github.com/ebashmakov/AzureApplicationInsightsNodesIssue/blob/master/AzureApplicationInsightsNodesIssue/Runner.cs

##  Actual Behavior
Increase the number of nodes -> **increase of costs**

![image](https://user-images.githubusercontent.com/970886/33397954-62724a64-d55e-11e7-8907-d677b2c16c27.png)
![image](https://user-images.githubusercontent.com/970886/33398013-86a15952-d55e-11e7-805e-ebd5df075b1e.png)

## Expected Behavior
The traces should not appear or at least they should have the same context as all other telemetry.
The number of nodes is not increased + no extra costs.

## Version Info 
SDK Version: `dotnet:2.4.0-32153`
.NET Version: `net461`
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension): `<PackageReference Include="Microsoft.ApplicationInsights" Version="2.4.0" />`
OS: `Windows`
Hosting Info (IIS/Azure WebApps/ etc): App Service (`WebApp` or `FunctionApp`)

**Comment by brettsam** [comment]
Are you creating your own TelemetryClient somewhere? That SDK version does not come from Functions -- it comes from the default TelemetryConfiguration.

Whenever you create your own TelemetryClient, use a new TelemetryConfiguration or else you'll get this. So, something like `new TelemetryClient(new TelemetryConfiguration())`

**Comment by ebashmakov** [comment]
@brettsam thanks, it helped! (I was creating the TelemetryClient manually - https://github.com/ebashmakov/AzureApplicationInsightsNodesIssue/blob/master/AzureApplicationInsightsNodesIssue/Runner.cs#L20)

So does this weird telemetry come from one of the default telemetry modules? Do you know which one?
What if I want to apply settings from ApplicationInsights.config file?

**Comment by brettsam** [comment]
In short, it's the `DiagnosticsTelemetryModule`. If you can follow along with this chain :-) -- 

The log message comes from here: https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/60a8d3f325e02503a4491d1a48cd70f9e5237a41/Src/PerformanceCollector/Perf.Shared/Implementation/PerformanceCollectorEventSource.cs#L151, which is an event being written out when a perf counter is not supported. In order to see that error, something needs to be listening for that event and logging it. When you create your own `TelemetryConfiguration`, nothing is listening, so you don't see that event anywhere.

However, if you do not specify a `TelemetryConfiguration`, App Insights uses `TelemetryConfiguration.Active`. That is initialized here: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/Microsoft.ApplicationInsights/Extensibility/TelemetryConfiguration.cs#L89.

If you follow `TelemetryConfigurationFactory.Initialize`, you can see the `DiagnosticsTelemetryModule` gets registered: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/Microsoft.ApplicationInsights/Extensibility/Implementation/TelemetryConfigurationFactory.cs#L61

And if you look at the `DiagnosticsTelemetryModule`, you can see that it eventually wires up an EventListener that listens to everything that starts with `Microsoft-ApplicationInsights-`: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Tracing/DiagnosticsEventListener.cs#L45.

So, normally you don't get this event logged anywhere, but if you allow the default configuration to be created, you'll end up with a listener that sends the event to your logs.

For your second question -- functions does not process the AppInsights.config file (currently; we may investigate this), so it will have no effect.

**Comment by ebashmakov** [comment]
@brettsam thanks for the detailed explanation.

I've noticed that `TelemetryConfiguration.Active` has 1 initializer and 1 processor by default:

- Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer
- Microsoft.ApplicationInsights.Extensibility.Implementation.TransmissionProcessor

But when I create my own `TelemetryConfiguration` it has only `TransmissionProcessor` and no `OperationCorrelationTelemetryInitializer`. I have to add `OperationCorrelationTelemetryInitializer` manually, right?
