### ISSUE TITLE
Exceptions don't have Operation Name when they happen after await ConfigureAwait(false)

### ISSUE THREAD

**Issue by zakimaksyutov** [Microsoft/ApplicationInsights-dotnet-server#759]
Exceptions/Dependencies collected after await ConfigureAwait(false) don't have Operation Name populated. Correlation Id/ParentId fields are populated properly.

## Repro Steps

```
public async Task<string> GetString()
{
    try
    {
        using (var client = new HttpClient())
        {
            var response = await client
                .GetStringAsync($"http://localhost/api/backend/GetStringFromBackend")
                .ConfigureAwait(false); // this line causes issues
            return response;
        }
    }
    catch (Exception ex)
    {
        this.telemetry.TrackException(ex);
        var response = new HttpResponseMessage(HttpStatusCode.InternalServerError)
            {
                Content = new StringContent($"Reference ID: {Guid.NewGuid()}", Encoding.UTF8)
            };
        throw new HttpResponseException(response);
    }
}
```

## Impact

User experience which depends on Operation Name (Performance/Failure UX) don't work properly.

## Reason

[OperationNameTelemetryInitializer](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/75373e57dcf8d646c54ee188461c373f2cc98939/Src/Web/Web.Shared.Net/OperationNameTelemetryInitializer.cs) uses HttpContext.Current (via [WebTelemetryInitializerBase](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/75373e57dcf8d646c54ee188461c373f2cc98939/Src/Web/Web.Shared.Net/Implementation/WebTelemetryInitializerBase.cs#L67)) which doesn't survive await ConfigureAwait(false).

## Workaround

Not use ConfigureAwait(false)

**Comment by zakimaksyutov** [comment]
cc @Dmitry-Matveev @lmolkova

**Comment by zakimaksyutov** [comment]
@lmolkova, I can see that Id/ParentId are propagated properly through ConfigureAwait(false). I wonder whether it is possible to migrate population of Operation Name to the same technology?

**Comment by lmolkova** [comment]
Indeed, OperationName is set from the HttpContext.Current that does not survive async calls.
What survives is Activity.Current (that hold Ids and ParentId).  So potentially Activity could be used to hold OperationName.
Beside correlation-ids, Activity has 
- `OperationName`, no, we cannot use it here :( as it's created by the instrumentation site and could not be changed. It is a coarse name like `Microsoft.AspNet.HttpRequestIn`.
- `Baggage` - key-value pairs that provide additional context about the operation. No, we cannot use them as baggage is propagated with external dependency calls.
- `Tags` - key-value pairs that provide additional context for current Activity only. They seem like the best fit for OperationName with one caveat: users may create activities that inherit from the request and become parent of the dependency: I.e. 
  1. Request Telemetry was tracked with `GET /api/values` OperationName, AI may add a tag to corresponding Activity with the name.
  2. When DependencyTelemetry is tracked it has to look for the first parent having this special tag, not necessarily it's immediate parent. Considering that UX does not support this case at all, not sure if it's important corner case.

In fact, this approach is already implemented with Base SDK [OperationCorrelationTelemetyIntiializer](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/7321d2bf7b9c4733fb43b6c186e381863931eb1a/src/Microsoft.ApplicationInsights/Extensibility/OperationCorrelationTelemetryInitializer.cs). I'll check why it does not work and will let you know the result.

**Comment by lmolkova** [comment]
@zakimaksyutov 

**What happens**

Base OperationCorrelationTelemetryInitializer uses "OperationName" Tag on the Activity. If child telemetry is initialized and initializer finds this tag on the parent Activity, it will set context.operation.name to it.

This tag is only set by StartOperation method (i.e. custom operation tracking). I.e. Web SDK does not set this Tag and therefore it is not propagated by OperationCorrelationTelemetryIntializer.

**How can we fix that**

The problem here is that OperationName is guaranteed to be calculated correctly only somewhere in RequestHandler (i.e. in a controller). See more on this here: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/393.

RequestTelemetry.context.operation.name is calculated only after request is processed in HttpModule.EndRequest event.

So, If child telemetry is reported within controller code, we can calculate name and be sure it will match RequestTelemetry.op.name.

However, if it is reported from another HttpModule, routes are not yet calculated by ASP.NET and name will not match RequestTelemetry.op.name. E.g. child telemetry name - 'GET /api/default/1' and request telemetry name - GET default [id].

So, I do not see a way to satisfy a requirement that child telemetry operation name should match root operation name.

We can sacrifice child telemetry that is reported outside of the controller though assuming it's the most interesting. 
Still, it's not a straightforward task to understand when routes are finally calculated and we can set a tag on activity, but it should be solvable. 

Let me know what you think and if you need more details on this.

**Comment by lmolkova** [comment]
@zakimaksyutov @SergeyKanzhelev @Dmitry-Matveev 
I think my main question is: 
As we cannot always satisfy the requirement that childTelemetry.Context.Operation.Name == rootTelemetry.Context.Operation.Name, why this requirement exists? Can we live without it and can we build UX without it?

Perhaps yes, as we can discover rootTelemetry.Context.Operation.Name based on the correlation Ids.

**Comment by SergeyKanzhelev** [comment]
`Operation.Name` (semantically) was designed as a mechanism to do impact analysis. Bad naming aside the idea was that `Request`'s name will be an `Operation.Name` for all telemetry inside the request (note, not an immediate parent's name). And when operation crossing the boundary of the component (dependency call) - `Operation.Name` of the next `Request` will also be the name of a previous `Request`.

You can look at it as the next level of naming hierarchy. Instrumentation Kay has many Role Names. Every Role Name has many Operations. Operations are connected with each others...

De-normalization (setting it for child telemetry items) was needed to simplify impact analysis queries like "which operations were affected by exceptions with this problem id?". With the joins support in Kusto it is irrelevant and I agree with @lmolkova we can stop collecting it.

De-normalization in cross-components case may be helpful. It will allow to do proper pre-aggregations. However this scenario is not supported today neither in SDK nor in UI. And it may never be implemented out of the box due to privacy concerns. Operation Name may contain user ID or other identifiers that application may not want to expose to dependencies.

So I'd also suggest to stop relying on Operation.Name and remove collection of it.

@zakimaksyutov @Dmitry-Matveev thoughts?

**Comment by zakimaksyutov** [comment]
cc @OsvaldoRosado 

@lmolkova, good question! We have one UX which relies on it. Let us dig deeper and understand whether we can achieve the same with correlation.

**Comment by MS-TimothyMothra** [comment]
@zakimaksyutov @OsvaldoRosado Have you determined that we need the operation name?
